#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}

#---------------------------------#
#    environment configuration    #
#---------------------------------#

image: Visual Studio 2017

platform:
  - x64
#  - Any CPU

configuration:
 - Debug
 - Release

build:
  parallel: true
  project: examples/sralloc.sln

#---------------------------------#
#       tests configuration       #
#---------------------------------#

test_script:
  -  C:\projects\sralloc\examples\Build\x64_%CONFIGURATION%g\unittest.exe
  - '%APPVEYOR_BUILD_FOLDER%\examples\build\%PLATFORM%_%CONFIGURATION%\unittest.exe'

# to disable automatic tests
#test: off
on_finish:
  - dir /s %APPVEYOR_BUILD_FOLDER%\examples\build
